### ISSUE TITLE
iksolver_pos max number of iterations and precision should be a parameter

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/kinematics-dynamics#100]
As can be seen, https://github.com/roboticslab-uc3m/kinematics-dynamics/commit/dcce8fd3361af10c29ee3766ea84eca349e416f2 is just a hard-coded hack.

**Comment by PeterBowman** [comment]
Done, new .ini parameters are: `maxIter` (max number of iterations) and `eps` (precision).

**Comment by jgvictores** [comment]
@PeterBowman Thank you so very much!!
