### ISSUE TITLE
Issue non-blocking movements and create new wait() command

### ISSUE THREAD

**Issue by PeterBowman** [roboticslab-uc3m/kinematics-dynamics#106]
At the time of writing, you cannot issue a `stopControl` command during a blocking operation like `movj`, `relj` or `movl` (see [BasicCartesianControl/ICartesianControlImpl.cpp](https://github.com/roboticslab-uc3m/kinematics-dynamics/blob/8c1e7b04e1ea9471794634626fc28c96ed55a2e6/libraries/TeoYarp/BasicCartesianControl/ICartesianControlImpl.cpp)) without creating a new client instance.

My proposal: make these RPC commands return immediately, and add a new `wait` method to the `ICartesianControl` interface (as in [CartesianServerLib/xRpcResponder.cpp](https://github.com/roboticslab-uc3m/asibot-main/blob/c975cd5b6e049be9a59e1c11b807faefe51fee6f/src/libraries/CartesianServerLib/xRpcResponder.cpp#L35-L52) at old asibot-main code). We'd have to deal with restoring previous reference speeds *after* the command has finished execution ([ref](https://github.com/roboticslab-uc3m/kinematics-dynamics/blob/8c1e7b04e1ea9471794634626fc28c96ed55a2e6/libraries/TeoYarp/BasicCartesianControl/ICartesianControlImpl.cpp#L131-L135)).

**Comment by jgvictores** [comment]
LGTM!

**Comment by PeterBowman** [comment]
BTW `movl` and similar commands currently return `VOCAB_OK` even if the cmc was forced to abort, e.g. because of exceeding the hardcoded joint velocity limit. The proposed `wait` command could take care of this and return failure vocabs in such circumstances.

**Comment by PeterBowman** [comment]
Cf. `yarp::dev::ICartesianControl::waitMotionDone`:

http://www.yarp.it/classyarp_1_1dev_1_1ICartesianControl.html#af1a253cb67ed5cf091854a58248e6446

**Comment by jgvictores** [comment]
LGTM!

**Comment by PeterBowman** [comment]
The wait period is no longer hardcoded, we can now tweak it on runtime via RPC config params: 1f62c00 (https://github.com/roboticslab-uc3m/kinematics-dynamics/issues/121#issuecomment-362797658).

**Comment by jgvictores** [comment]
Cool!!!

**Comment by PeterBowman** [comment]
Hmmm. Having a timeout is nice, but it's designed to work only on the server side. If network delays/errors occur, how can I enforce a timeout on the client side, too?

**Comment by jgvictores** [comment]
- Delays: well, we just wait some more.
- Disconnection: tried a `yarp rpc` (client) against a read port (emulates a server, as `yarp rpc --server` is not working). Writing something from the client, awaiting for response, then killing the read port actually makes the client die:
   > yarp: BottleImpl reader failed, unrecognized object code 25
   > Cannot make connection
   > yarp: Alternative method: precede port name with --client

This is, I think server-side wait is enough.

**Comment by PeterBowman** [comment]
Nice to know that, thanks!
