### ISSUE TITLE
Implement tool-related methods in AsibotSolver

### ISSUE THREAD

**Issue by PeterBowman** [roboticslab-uc3m/kinematics-dynamics#108]
That is:

- [x] `appendLink(const std::vector<double> &)`
- [x] `restoreOriginalChain()`

And add their corresponding unit tests in `testAsibotSolverFromFile`, too.

**Comment by PeterBowman** [comment]
`appendLink` and `restoreOriginalChain` could be implemented quite easily with the latest improvements, particularly #141.  Dynamics are a different beast, and AmorCartesianControl also lacks an implementation of `invDyn`-related commands. I'm prone to leaving them out of this issue and tracking their development in a new ticket.

**Comment by jgvictores** [comment]
> Dynamics are a different beast, and AmorCartesianControl also lacks an implementation of invDyn-related commands. I'm prone to leaving them out of this issue and tracking their development in a new ticket.

+1

**Comment by PeterBowman** [comment]
Both overloads of the `invDyn` method have been moved to #142, description updated accordingly.

**Comment by PeterBowman** [comment]
Done at a12a9dd.
