### ISSUE TITLE
Teo-head compilation error

### ISSUE THREAD

**Issue by rsantos88** [roboticslab-uc3m/kinematics-dynamics#12]
Compilation error with teo-head code:

[  7%] Built target HeadYarp
[ 14%] Building CXX object programs/cv1/CMakeFiles/cv1.dir/Cv1.cpp.o
In file included from /home/teo/git/teo-head/programs/cv1/SegmentorThread.hpp:14:0,
                 from /home/teo/git/teo-head/programs/cv1/Cv1.hpp:6,
                 from /home/teo/git/teo-head/programs/cv1/Cv1.cpp:3:
/usr/local/include/yarp/dev/IOpenNI2DeviceDriver.h:16:18: fatal error: NiTE.h: No existe el archivo o el directorio
 #include <NiTE.h>
                  ^
compilation terminated.
programs/cv1/CMakeFiles/cv1.dir/build.make:77: recipe for target 'programs/cv1/CMakeFiles/cv1.dir/Cv1.cpp.o' failed
make[2]: **\* [programs/cv1/CMakeFiles/cv1.dir/Cv1.cpp.o] Error 1
CMakeFiles/Makefile2:282: recipe for target 'programs/cv1/CMakeFiles/cv1.dir/all' failed
make[1]: **\* [programs/cv1/CMakeFiles/cv1.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: **\* [all] Error 2

**Comment by jgvictores** [comment]
Issue moved to https://github.com/roboticslab-uc3m/teo-head/issues/4
