### ISSUE TITLE
SWIG chokes on ROBOTICSLAB_KINEMATICS_DYNAMICS_DEPRECATED

### ISSUE THREAD

**Issue by RaulFdzbis** [roboticslab-uc3m/kinematics-dynamics#132]
swig chokes on ROBOTICSLAB_KINEMATICS_DYNAMICS_DEPRECATED

just try to include ICartesianSolver.h in bindings

**Comment by RaulFdzbis** [comment]
PS: blame @jgvictores

**Comment by RaulFdzbis** [comment]
Hack for 9f396c0 at 78683cb

**Comment by PeterBowman** [comment]
Done at cdc0133.

**Comment by PeterBowman** [comment]
For the record, this is the error thrown when trying to compile the bindings for `ICartesianControl`:

```
/usr/local/include/ICartesianSolver.h:41: Error: Syntax error in input(3).
```

Line 41 refers to:

https://github.com/roboticslab-uc3m/kinematics-dynamics/blob/9f396c0a0c75e962f7fc7f46bce0297bc96a6c42/libraries/YarpPlugins/ICartesianSolver.h#L41-L45
