### ISSUE TITLE
Refactor CMake files

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/kinematics-dynamics#14]
A great number of new CMake features would make our CMake files cleaner and better.

**Comment by PeterBowman** [comment]
I've noticed that most CMake files still set a minimum required version of 2.6.x, which should be raised to benefit from newer features. This could be discussed at a global (roboticslab) level since teo-main is not the only project affected.

**Comment by jgvictores** [comment]
Yes, I'd propose:
- Match the CMake version supported by YARP
- Document this on whatever comes out of https://github.com/roboticslab-uc3m/QA/issues/4
- Update cmake files of https://github.com/roboticslab-uc3m/project-generator

**Comment by PeterBowman** [comment]
Related: roboticslab-uc3m/QA#7.

**Comment by PeterBowman** [comment]
Done at 6f90a96. Minimum required CMake version has been bumped to 2.8.11 to allow making use of the handy [`target_include_directories()`](https://cmake.org/cmake/help/v3.0/command/target_include_directories.html) command.

**Comment by PeterBowman** [comment]
> Minimum required CMake version has been bumped to 2.8.11...

Bumped to 3.1.3, see ca84df0.
