### ISSUE TITLE
[exampleCartesianControlClient] change delays for new wait function

### ISSUE THREAD

**Issue by rsantos88** [roboticslab-uc3m/kinematics-dynamics#144]
As a followup of #143, change delays for new wait function!

**Comment by rsantos88** [comment]
sorry for update the changes directly on develop branch, but it works very well :) (cb0ecbe615f08fb6dd66f8436dff394faaff81c3)
I'll close this issue

**Comment by jgvictores** [comment]
Cool!

**Comment by rsantos88** [comment]
I've given myself the freedom to modify the `cpp` example with some of this changes (809569077263756eb8278f93e0b7df12e30566bb)
* more control error on `movj` 
* `0.0` instead of `1.234e-17`

**Comment by jgvictores** [comment]
Perfect, thanks!
