### ISSUE TITLE
[tests] Fix KdlSolverInvDyn2 and KdlSolverInvDyn3

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/kinematics-dynamics#15]
KdlSolverInvDyn2 and KdlSolverInvDyn3 dynamics tests fail, possibly since H0 and HN were added. Please review and fix.

**Comment by rsantos88** [comment]
The value returned by the function: "int CartToJnt(const JntArray &q, const JntArray &q_dot, const JntArray &q_dotdot, const Wrenches& f_ext,JntArray &torques);" in the line 145 of ICartesianSolverImpl.cpp is '-1'.
This function has been defined in KDL Library, on "chainidsolver_recursive_newton_euler.cpp" file and this result means:
//! Failed to converge
        E_NO_CONVERGE      = -1,

**Comment by jgvictores** [comment]
Thanks. With commit 107d93dd627fa8ccf7be575567ac6db5d2e184ec we now have explicit prints of this error and similar ones.
Bug not fixed yet.

**Comment by jgvictores** [comment]
It turns out that chainidsolver_recursive_newton_euler.cpp returns a -1 in a very different scenario:
https://github.com/orocos/orocos_kinematics_dynamics/blob/707ce2c58a1af628696b3c3828de98bf30f63366/orocos_kdl/src/chainidsolver_recursive_newton_euler.cpp#L37-L38

**Comment by jgvictores** [comment]
Put issue upstream: https://github.com/orocos/orocos_kinematics_dynamics/issues/78

**Comment by jgvictores** [comment]
So... from https://github.com/orocos/orocos_kinematics_dynamics/blob/707ce2c58a1af628696b3c3828de98bf30f63366/orocos_kdl/src/chainidsolver_recursive_newton_euler.cpp#L37-L38
We see that the error is probably due to our H0 and HN. Actually, commenting out https://github.com/roboticslab-uc3m/teo-main/blob/e898d0f6e146126ceceb120b8c563d0fc3aa0cf7/libraries/TeoYarp/KdlSolver/DeviceDriverImpl.cpp#L42 and https://github.com/roboticslab-uc3m/teo-main/blob/e898d0f6e146126ceceb120b8c563d0fc3aa0cf7/libraries/TeoYarp/KdlSolver/DeviceDriverImpl.cpp#L133 allows Dyn tests to pass.

**Comment by jgvictores** [comment]
In fact is fixed with simple patch: https://github.com/jgvictores/orocos_kinematics_dynamics/commit/d20c9d11e6a0c04c63a6b684a1351eed055b588b (lines are a bit different in current KDL, but patch could be updated).

**Comment by jgvictores** [comment]
Fixed at 5043d8c74804f2bf95fa5320efca2cf553bd2a0e by using a combination of KDL `chain.getNrOfJoints()` and `chain.getNrOfSegments()` (note that `segments` > `joints` if there are `Joint::None`).
