### ISSUE TITLE
Returning values out of joint limits

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/kinematics-dynamics#153]
Returning values out of joint limits, at least with https://github.com/roboticslab-uc3m/teo-configuration-files/blob/cf9bb81817ec1d92228a524adaffcc5505d64589/share/kinematics/trunkAndRightArmKinematics.ini result of https://github.com/roboticslab-uc3m/teo-configuration-files/issues/12

**Comment by PeterBowman** [comment]
Spoke f2f and not sure about this. Values seem fine.

**Comment by jgvictores** [comment]
Yes, closing. I think it was a deg/rad confusion.
