### ISSUE TITLE
Embrace GitFlow

### ISSUE THREAD

**Issue by David-Estevez** [roboticslab-uc3m/kinematics-dynamics#16]
Discuss whether it would be useful or not to use the [GitFlow git workflow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow) to improve repository organization and coordination between contributors.

**Comment by jgvictores** [comment]
We have released https://github.com/roboticslab-uc3m/teo-main/releases/tag/v1.0.0 which corresponds to 81eb017afc89ac7486353c43bd60bcc0a1fb78ce. Forking and GitFlow will be the recommended practices from now on.

**Comment by jgvictores** [comment]
Closed at 5d6639152275fa459ffe9f68b1a4a8b36998f6a1 together with previous reorganization and tag.
