### ISSUE TITLE
IK through infinitesimal displacement twists

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/kinematics-dynamics#171]
Proposed [here](https://github.com/roboticslab-uc3m/kinematics-dynamics/issues/119#issuecomment-351735714) by @PeterBowman: IK through infinitesimal displacement twists ([Bruyninckx, *Robot Kinematics and Dynamics*, 4.1.8](https://people.mech.kuleuven.be/~bruyninc/tmp/HermanBruyninckx-robotics.pdf)), which somehow resemble virtual displacements, and then solve the usual delta_q = J^-1 * delta_x equation (note the deltas instead of time derivatives).

**Comment by PeterBowman** [comment]
Closing as invalid. Take a look at the implementation of [`KDL::ChainIkSolverPos_NR_JL::CartToJnt`](http://docs.ros.org/lunar/api/orocos_kdl/html/classKDL_1_1ChainIkSolverPos__NR__JL.html): what I wanted to achieve can be already done by instantiating our *KdlSolver* device with `--ik nrjl --maxIter 1`.

**Comment by PeterBowman** [comment]
My bad, the KDL implementation of NR is going to return a `E_MAX_ITERATIONS_EXCEEDED` error with that setup ([ref](http://docs.ros.org/lunar/api/orocos_kdl/html/chainiksolverpos__nr__jl_8cpp_source.html#l00062)). It has to be reimplemented, then, without that for-loop (and with no epsilon check). Also, the IK velocity solver might throw an error ([ref](http://docs.ros.org/lunar/api/orocos_kdl/html/svd__HH_8cpp_source.html#l00060)) due to exceeding the maximum number of iterations in the SVD step. I wonder if this could be avoided no mather what. Beware of singular Jacobian pseudoinverses, too.

**Comment by PeterBowman** [comment]
@jgvictores BTW OK to rename `nrjl` to simply `nr`? (`jl` stands for "joint limits", which I deem an implementation detail; KDL provides another Newton-Raphson solver without taking those into account, whereas we use the *full* version)

**Comment by jgvictores** [comment]
Perfectly agree!

**Comment by jgvictores** [comment]
Samuel R. Buss "Introduction to Inverse Kinematics with Jacobian Transpose, Pseudoinverse and Damped Least Squares methods" https://www.math.ucsd.edu/~sbuss/ResearchWeb/ikmethods/iksurvey.pdf

**Comment by PeterBowman** [comment]
Implemented with a Jacobian transpose per https://github.com/roboticslab-uc3m/kinematics-dynamics/issues/171#issuecomment-453642345. The behavior is far from ideal: TEO's hands are kinda shaky in simulation, the TCP deviates 1-2 cm along a "linear" path (tested with *keyboardController*), and TCP-frame motion is mostly broken. @jgvictores not sure we can get any better, shall we merge this?

**Comment by jgvictores** [comment]
> @jgvictores not sure we can get any better, shall we merge this?

Let's go!

**Comment by PeterBowman** [comment]
> BTW OK to rename `nrjl` to simply `nr`? (`jl` stands for "joint limits", which I deem an implementation detail; KDL provides another Newton-Raphson solver without taking those into account, whereas we use the _full_ version)

Reverted in https://github.com/roboticslab-uc3m/kinematics-dynamics/commit/8d7a353fbb1e585db72fdb6f16f87cae195f71df. I forgot the `lmajl` thing we spoke about at https://github.com/roboticslab-uc3m/kinematics-dynamics/issues/128, thus keeping the `jl` suffix actually makes sense.
