### ISSUE TITLE
Align CMake code related to bindings with latest YARP

### ISSUE THREAD

**Issue by PeterBowman** [roboticslab-uc3m/kinematics-dynamics#189]
YARP 3.4 is out and introduces an important change: Python 2 is no longer supported. Consequently, it makes no sense to generate Python 2 bindings for the kinematics_dynamics module and later combine it with the Python 3 YARP module in the same Python script. Therefore, I suggest to update (at last) the dated CMake script we use for generating SWIG bindings ([ref](https://github.com/roboticslab-uc3m/kinematics-dynamics/blob/f35184e98b11738aafb6fafd4254bd70634d4606/bindings/CMakeLists.txt)), mirroring whatever YARP folks have implemented on their side ([ref](https://github.com/robotology/yarp/tree/3fec784e01259f944bb8fc60e17fdd698f4f5523/bindings)).

FYI see https://github.com/roboticslab-uc3m/installation-guides/commit/7a9134f9c1d39df4d980307c06c8fa6912dc9e62.

**Comment by jgvictores** [comment]
For reference, this was partially done (very python-oriented) at https://github.com/roboticslab-uc3m/vision/tree/01ce8ad6325198f48c3ada7de3462f0591d07872/bindings (mainly via https://github.com/roboticslab-uc3m/vision/commit/7497b4b07688aafa101889f5285abddc1c16c427 but further improved)
