### ISSUE TITLE
Avoid "using namespace"

### ISSUE THREAD

**Issue by rsantos88** [roboticslab-uc3m/kinematics-dynamics#22]
I think, we can add the some solution of Teo-Head and Teo-Body for resolve possible conflicts with namespaces that may appear in the future. Can someone resolve it??

**Comment by rsantos88** [comment]
Ok, now there are not “using namespace” in teo-main proyect and the code compiles without errors. However, there are some warnings of OpenRAVE that should be reviewed.

**Comment by jgvictores** [comment]
Done at https://github.com/roboticslab-uc3m/teo-main/pull/23
Thanks!
