### ISSUE TITLE
Unify robot model kinematics

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/kinematics-dynamics#28]
Issue inherited from wiki, where work has been done (resulting in [current TEO Diagrams](http://robots.uc3m.es/index.php/TEO_Diagrams)). The following is a list of models to potentially be merged or linked somehow.
- [x] Kinematics used by [KdlSolver](https://github.com/roboticslab-uc3m/teo-main/tree/master/libraries/TeoYarp/KdlSolver): ([.ini files that contain DH parameters](https://github.com/roboticslab-uc3m/teo-main/tree/master/share/kinematics)).
- [x] Kinematics used by [teo_batc](https://github.com/roboticslab-uc3m/teo_batc): ([Gazebo model](https://github.com/roboticslab-uc3m/teo-gazebo)), ([ROS Gazebo model](https://github.com/roboticslab-uc3m/teo-ros-simulation)).
- [x] Kinematics used by [teoSim](https://github.com/roboticslab-uc3m/teo-main/tree/master/programs/teoSim): ([Openrave model](https://github.com/roboticslab-uc3m/teo-main/tree/master/share/openrave/teo)).

**Comment by jgvictores** [comment]
@RaulFdzbis Can you check Gazebo 3D and Kinematics [teo_description](https://github.com/roboticslab-uc3m/teo_batc/tree/master/teo_description) follows the [current TEO Diagrams](http://robots.uc3m.es/index.php/TEO_Diagrams)?

**Comment by RaulFdzbis** [comment]
**Note:** The teo_description package have been moved to [teo-ros-simulation](https://github.com/roboticslab-uc3m/teo-ros-simulation), also there is a model of TEO to work with a **stand-alone** setup of Gazebo in [teo-gazebo](https://github.com/roboticslab-uc3m/teo-gazebo).

Modifications of models in accordance with this issue were done in [a6199bc](https://github.com/roboticslab-uc3m/teo-ros-simulation/commit/a6199bc965c44919686355d27d876d9e002fa77c) for the **teo-ros-simulation** package and [7718f22](https://github.com/roboticslab-uc3m/teo-gazebo/commit/7718f22c90b09dc30c5b4b4b55e1aa86e3c85566) for the **teo-gazebo** repository.

In addition the joint limitations of both models have been also updated in accordance to the last version of [teo-main](https://github.com/roboticslab-uc3m/teo-main/tree/master/share/kinematics).

**Comment by jgvictores** [comment]
@RaulFdzbis Thanks! Marked Gazebo part as done!

**Comment by jgvictores** [comment]
teoSim openrave was last missing, done at https://github.com/roboticslab-uc3m/teo-main/commit/e518e2c43aaeabb2350ad07e04c442169c2d9962.
