### ISSUE TITLE
Unify robot model dynamics

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/kinematics-dynamics#29]
Issue inherited from wiki, where work has been done (resulting in [current TEO Diagrams](http://robots.uc3m.es/index.php/TEO_Diagrams)). The following is a list of models to potentially be merged or linked somehow.
- [ ] Kinematics(DH)+Mass/Inertia used by [KdlSolver](https://github.com/roboticslab-uc3m/kinematics-dynamics/tree/8d798ca1b44df125fd404261ca04996641738a83/libraries/TeoYarp/KdlSolver): [[1]](https://github.com/roboticslab-uc3m/teo-configuration-files/tree/9f08cf2e0a121ab0d714bea6cdb8ed295de9593c/share/kinematics).
- [ ] OpenRAVE 3D and Kinematics used by [teoSim](https://github.com/roboticslab-uc3m/openrave-yarp-plugins/tree/c4d034feed12e7ad010cebb38ca468e1d1054aca/programs/teoSim): [[2]](https://github.com/roboticslab-uc3m/teo-openrave-models/tree/b165a392a8700b73c9baf5bff7ea3caf114564b8/openrave/teo)
- [ ] Gazebo 3D and Kinematics+Mass/Inertia used by [teo-ros-simulation](https://github.com/roboticslab-uc3m/teo-ros-simulation): [[3]](https://github.com/roboticslab-uc3m/teo-ros-simulation/tree/fe3147dc5c5638d8239b7c8417a58b2eb5ac9185/teo_description)

For future reference, links to Mass/Inertia (official based on mechanical schematics): [.XLS](http://robots.uc3m.es/svn/TEOrepo/modelling/dynamics/Inercias_090518.xls) and [.PDF](http://robots.uc3m.es/svn/TEOrepo/modelling/dynamics/Inercias_090518.pdf).

*Updated on 16/08/17 by PeterBowman.*

**Comment by lpinel** [comment]
Added to [http://robots.uc3m.es/index.php/TEO_Diagrams](url) temporary Force-Torque Sensors Diagram wich includes sensors axes, location and connections to DAQ card.

**Comment by PeterBowman** [comment]
This issue was moved to roboticslab-uc3m/teo-main#16
