### ISSUE TITLE
Unify robot model joint limits

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/kinematics-dynamics#31]
Should be in wiki, where work has been done (resulting in [current TEO Diagrams](http://robots.uc3m.es/index.php/TEO_Diagrams)). The following is a list of models to potentially be merged or linked somehow.
- [ ] Real joint limits are in [.ini of launch files in teo-body](https://github.com/roboticslab-uc3m/yarp-devices/tree/891b31117a7f703ff2f367832e42d36e8d164c86/share), should be the same across files.
- [ ] Kinematics used by [KdlSolver](https://github.com/roboticslab-uc3m/kinematics-dynamics/tree/8d798ca1b44df125fd404261ca04996641738a83/libraries/TeoYarp/KdlSolver): ([.ini files that contain DH parameters](https://github.com/roboticslab-uc3m/teo-configuration-files/tree/9f08cf2e0a121ab0d714bea6cdb8ed295de9593c/share/kinematics)). Perhaps could be removed from here?
- [x] Kinematics used by [teo_batc](https://github.com/roboticslab-uc3m/teo_batc): ([Gazebo model](https://github.com/roboticslab-uc3m/teo-gazebo)), ([ROS Gazebo model](https://github.com/roboticslab-uc3m/teo-ros-simulation)).
- [ ] Kinematics used by [teoSim](https://github.com/roboticslab-uc3m/openrave-yarp-plugins/tree/c4d034feed12e7ad010cebb38ca468e1d1054aca/programs/teoSim): ([Openrave model](https://github.com/roboticslab-uc3m/teo-openrave-models/tree/65b36e548bc25e7d4c413c822df9819c414bbfef/openrave/teo)).

*Updated on 16/08/17 by PeterBowman.*

**Comment by RaulFdzbis** [comment]
[Gazebo model](https://github.com/roboticslab-uc3m/teo-gazebo) and [Ros Gazebo model](https://github.com/roboticslab-uc3m/teo-ros-simulation), were already updated in [7718f22](https://github.com/roboticslab-uc3m/teo-gazebo/commit/7718f22c90b09daludo.c30c5b4b4b55e1aa86e3c85566) and [a6199bc](https://github.com/roboticslab-uc3m/teo-ros-simulation/commit/a6199bc965c44919686355d27d876d9e002fa77c) with the joint limits used by the KdlSolver in [teo_main](https://github.com/roboticslab-uc3m/teo-main/tree/master/share/kinematics).

**Comment by PeterBowman** [comment]
This issue was moved to roboticslab-uc3m/teo-main#15
