### ISSUE TITLE
Lista de objetos que hay que llevar para RoboCity

### ISSUE THREAD

**Issue by rsantos88** [roboticslab-uc3m/kinematics-dynamics#32]
Lista de objetos que hay que llevar:
- [x] Teo
- [x] Grúa o soporte para sostener a Teo, con su cargador en caso de ser la nueva
- [x] Fuentes de alimentación de Teo (no separar, ambas van conectadas en paralelo) con cables de alimentación.
- [x] Router para conectarse a Teo con cables ethernet: “head” y “main” y otro por si a caso.
- [x] PC “Teo-main” con teclado, ratón, monitor y cable de alimentación.
- [x] Monitor extra con cable VGA.
- [x] Teclado extra y ratón inalámbrico
- [x] Micrófono bluetooth
- [x] Botella de bici roja (se necesita llena de agua para la demo)
- [x] Opcional: Televisión LG grande con cable de alimentación, cable HDMI y mando.
- [x] Regletas (x2)
- [x] Herramientas para reparaciones rápidas: bridas, velcro, loctite, llaves allen, destornilladores...

Se admiten sugerencias si falta alguna cosa más por llevar @jgvictores @smcdiaz @jmgarciah @lpinel

**Comment by RaulFdzbis** [comment]
Si se lleva la grua nueva estaría bien llevar el cargador de la misma, por si acaso.

**Comment by David-Estevez** [comment]
Lo mismo habría que llevar herramientas para posibles ñapas que haya que hacer en directo. 
- [x] :wrench:
- [x] Loctite
- [x] Bridas 
- [x] Velcro

**Comment by jgvictores** [comment]
@rsantos88 he actualizado tu lista con el cargador que decía @RaulFdzbis

**Comment by rsantos88** [comment]
@jmgarciah también opina que deberíamos llevar material para hacer reparaciones rápidas: bridas, llaves allen, destornilladores...

**Comment by David-Estevez** [comment]
Buuuuh!! Que @jmgarciah comente él por aquí, que le echamos de menos!! :cry:

**Comment by jgvictores** [comment]
@jmgarciah Me incluyo en el listado de los que te extrañan vía GitHub. ¿Podrias por favor ampliar la lista que empezó MSc @David-Estevez?

**Comment by smcdiaz** [comment]
Se llevará una caja con herramientas pero a ver si somos capaces de no romper nada!! (cosa difícil....)

**Comment by smcdiaz** [comment]
Tranquis. Mañana preparo yo un kit básico de supervivencia robótica con muchas bridas, cinta aislante y, por supuesto, 'superglu'

**Comment by lpinel** [comment]
y la seta de emergencia ....

**Comment by jgvictores** [comment]
Conferenced passed, closing issue,
