### ISSUE TITLE
Teo list Wiki

### ISSUE THREAD

**Issue by RaulFdzbis** [roboticslab-uc3m/kinematics-dynamics#33]
It could be interesting to have some documentation/list in the Wiki (or other repository), similar to the one used [here](https://github.com/roboticslab-uc3m/teo-main/issues/32), to use it to save time in future events.

**Comment by jgvictores** [comment]
Sounds good to keep this near http://robots.uc3m.es/index.php/Procedimiento_Demos, linked from http://robots.uc3m.es/index.php/TEO#Links_of_General_Interest.

**Comment by jgvictores** [comment]
Creada http://robots.uc3m.es/index.php/Qu%C3%A9_llevar_a_Demos_%28TEO%29
Enlazada desde http://robots.uc3m.es/index.php/TEO#Links_of_General_Interest
