### ISSUE TITLE
Backdrop for robot pictures and videos in publications

### ISSUE THREAD

**Issue by David-Estevez** [roboticslab-uc3m/kinematics-dynamics#49]
I think it would be useful to have some cloth or curtain-like thing to use as a backdrop in Teo's cage when taking pictures or recording videos that are going to be published later. This would give a much better impression of the robot.

How could we solve this? Any ideas?

**Comment by jgvictores** [comment]
Moved to https://github.com/jgvictores/laboratorios/issues/9
