### ISSUE TITLE
Review dynamic models (masses, COGs and inertias)

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/kinematics-dynamics#6]
Review dynamic models (masses, COGs and inertias) currently in [teo-configuration-files/share/kinematics](https://github.com/roboticslab-uc3m/teo-configuration-files/tree/98bbc4aa181e21c2242dc915704432397534cab9/share/kinematics).

*Updated on 16/08/17 by PeterBowman.*

**Comment by jgvictores** [comment]
Correct left and right arm kinematics and masses at [`037752e`](https://github.com/roboticslab-uc3m/kinematics-dynamics/commit/037752e8d5e120e7fea1b0f77cdd17f7757240e9). COGs are approximate, and inertias are depreciated.

**Comment by PeterBowman** [comment]
This issue was moved to roboticslab-uc3m/teo-main#17
