### ISSUE TITLE
[TeoYarp] devices should be shared libraries

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/kinematics-dynamics#60]
[TeoYarp] devices should be shared libraries (same as https://github.com/roboticslab-uc3m/teo-body/issues/51 )

**Comment by jgvictores** [comment]
Tests are not passing on travis. Put issue upstream: https://github.com/robotology/QA/issues/148

**Comment by jgvictores** [comment]
Issue no longer upstream. Must implement.

**Comment by rsantos88** [comment]
Done it! #75

**Comment by jgvictores** [comment]
Finished at https://github.com/roboticslab-uc3m/teo-main/commit/b16ef4d5f2721683b45e8b5ba3045d48713cd5dd
