### ISSUE TITLE
Try and doc teoBase with grasping demo

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/kinematics-dynamics#66]
Try and doc teoBase with grasping demo.
- [ ] Try
- [ ] Doc at http://robots.uc3m.es/index.php/Procedimiento_Demos

**Comment by jgvictores** [comment]
@jmgarciah Is the grasping demo [manip-waiter](https://github.com/roboticslab-uc3m/manip-waiter)?

**Comment by jmgarciah** [comment]
No, It isn't. I have created a new branch "grasp" inside waiter repo. The goal is to replace the waiter demo for this new one.

**Comment by PeterBowman** [comment]
This issue was moved to roboticslab-uc3m/teo-main#14
