### ISSUE TITLE
Try and doc teoBase with walking demo

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/kinematics-dynamics#67]
Try and doc teoBase with walking demo.
- [ ] Try
- [ ] Doc at http://robots.uc3m.es/index.php/Procedimiento_Demos

**Comment by jgvictores** [comment]
Requires https://github.com/roboticslab-uc3m/teo-main/issues/53 first.

**Comment by jgvictores** [comment]
Originally set for NOV 01. :smile:

**Comment by PeterBowman** [comment]
Blocked by #53.

**Comment by jgvictores** [comment]
This issue was moved to roboticslab-uc3m/teo-main#12
