### ISSUE TITLE
Teo- main no permite hacer:    sudo make uninstall

### ISSUE THREAD

**Issue by rsantos88** [roboticslab-uc3m/kinematics-dynamics#80]
Actualmente, teo-main no permite realizar una desinstalación limpia (como si nos lo permite teo-body o teo-head) haciendo uso del comando: 
`sudo make uninstall`
Nos mostraría por consola el siguiente error:
```bash
make: *** No rule to make target 'uninstall'.  Alto.
```

**Comment by jgvictores** [comment]
Blame @munozyanez en b2f2538 :smile:

Recuperado en ee2b44a (current branch `issue-80-uninstall`). Por favor, prueba y me comentas.

**Comment by rsantos88** [comment]
Perfecto!! Ya funciona!!
Gracias @jgvictores !! :smile:
