### ISSUE TITLE
Imminent repo name change (teo-main -> kinematics-dynamics)

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/kinematics-dynamics#82]
On Friday March 3rd 2017 evening, this repo will be renamed: teo-main -> kinematics-dynamics

Related with roboticslab-uc3m/QA#2 and https://github.com/orgs/roboticslab-uc3m/projects/2

As a consequence, in addition to migration of corresponding issues, we'll try to remove large TEO models from the git history.

Cheers!

**Comment by munozyanez** [comment]
I have an issue ready to go for teo-main/twolimbcc.
What do you prefer : 1. Open issue in teo-main and migrate whenever with the others, or 2. Close the fork with PR, then open the issue in new repo (kinematics-dynamics)?

**Comment by jgvictores** [comment]
Feel free to merge the PR as in option 2. I'm sure it won't break anything. Then put the issue describing the current state of development on however the repo is called at time of writing. 

It's technically possible to do option 1, but let's keep things simple.

Thanks!

**Comment by munozyanez** [comment]
Ok, pull request ready.

**Comment by jgvictores** [comment]
Please check my comment on the PR.

**Comment by munozyanez** [comment]
I am trying with that:

Step 1: From your project repository, bring in the changes and test.

git fetch origin
git checkout -b twolimbcc origin/twolimbcc
git merge develop

Step 2: Merge the changes and update on GitHub.

git checkout develop
git merge --no-ff twolimbcc
git push origin develop

**Comment by jgvictores** [comment]
- Merge performed.
- Renaming done. :smile:

**Comment by munozyanez** [comment]
Great!
I am testing the code and giving feedback in no time.

**Comment by munozyanez** [comment]
For teoSim, I had to reconfigure that lines:
#define DEFAULT_ENV "../openrave/teo/teo.robot.xml" 
to
 #define DEFAULT_ENV "contexts/openrave/teo/teo.robot.xml"
in order to allow the program to find the robot files, installed from the new repo (teo-openrave-models).
I do not know the intentions with folders, so I keep it as a workaround until known.

**Comment by jgvictores** [comment]
@munozyanez Okay, I've hard-coded that at https://github.com/roboticslab-uc3m/kinematics-dynamics/commit/4fc24d4b3cec3b11eee5d4682266ab203b35c2f2
Wouldn't worry too much; as stated in [teo-software-manual](https://github.com/roboticslab-uc3m/teo-software-manual/tree/01d5ed521257fc8d1d59493f92eaf4820db23ca3), we'll soon be moving on to https://github.com/roboticslab-uc3m/openrave-yarp-plugins

**Comment by munozyanez** [comment]
I see that launchTeoYarp executable is commented now in cmake code. Is there any plan to change its behavior?

**Comment by PeterBowman** [comment]
@munozyanez it was superseded by `yarpdev` when we started using dynamically loaded plugins, call `yarpdev --device name_of_plugin` just as you would have done with `launchTeoYarp`. This is the same reason `yarp_begin_plugin_library` and `yarp_end_plugin_library` were commented out, too.

**Comment by munozyanez** [comment]
Ah, ok. Thanks a lot @PeterBowman

**Comment by munozyanez** [comment]
Done testing on BasicTwoLimbCartesianControl. Everything working as usual in teo-main.

**Comment by jgvictores** [comment]
All done here.
