### ISSUE TITLE
FindGAIT.cmake is too hard-coded

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/kinematics-dynamics#91]
FindGAIT.cmake is too hard-coded, especially [this line](https://github.com/roboticslab-uc3m/kinematics-dynamics/blob/fix-90-travis/cmake/FindGAIT.cmake#L8) if it ever makes it into `develop`.

**Comment by PeterBowman** [comment]
We could get rid of `FindGAIT.cmake` if Gait started using the `export(PACKAGE)` command ([docs](https://cmake.org/cmake/help/v3.0/command/export.html)). Or keep it as a fallback.

**Comment by jgvictores** [comment]
Yes, I totally agree. This is yet another of those issues that are mainly intended to remember what is where. :slightly_smiling_face:

**Comment by PeterBowman** [comment]
`FindGAIT.cmake` is gone for good after the last CMake code review: 6f90a96. Downstream maintainers can find an updated usage guide in README.md at https://github.com/roboticslab-uc3m/gait.
