### ISSUE TITLE
Extract and import ASIBOT's analytical cartesian solver from asibot-main repo

### ISSUE THREAD

**Issue by PeterBowman** [roboticslab-uc3m/kinematics-dynamics#96]
Currently implemented as a `yarp::dev::ICartesianControl` ([path](https://github.com/roboticslab-uc3m/asibot-main/tree/c2644a2/src/libraries/RlPlugins/cartesianbot)), should be stripped from any control loops and repurposed as a `teo::ICartesianSolver`.

Full migration plan: roboticslab-uc3m/asibot-main#28.

**Comment by PeterBowman** [comment]
WIP at the `asibot-cartesian-solver` branch.

**Comment by PeterBowman** [comment]
Just wanted to note that there are some conversion operations left in [CartesianServerLib/xCallbackPort.cpp](https://github.com/roboticslab-uc3m/asibot-main/blob/310d5dc/src/libraries/CartesianServerLib/xCallbackPort.cpp) at which I'd like to take a look.

**Comment by PeterBowman** [comment]
CartesianBot implements tool tip calculations, but we lack a proper interface. Perhaps blocked until #95 is resolved?

**Comment by jgvictores** [comment]
> CartesianBot implements tool tip calculations, but we lack a proper interface. Perhaps blocked until #95 is resolved?

Yes, I agree.

**Comment by PeterBowman** [comment]
The [`TrajGen.h`](https://github.com/roboticslab-uc3m/kinematics-dynamics/blob/31c635d/libraries/TeoYarp/AsibotSolver/TrajGen.hpp) library I've imported along with ASIBOT's solver could be easily replaced by [KDL::VelocityProfile_Spline](http://docs.ros.org/hydro/api/orocos_kdl/html/classKDL_1_1VelocityProfile__Spline.html).

**Comment by PeterBowman** [comment]
Good enough at 974de24, follow-ups include:

* #108 (unimplemented `ICartesianControl` methods)
* #109 (investigate singularities)
* #110 (enhance unit tests)
* #111 (don't restrict rotations to 180º)
* #112 (apply custom world and tool reference frames)

I've left the [TrajGen.hpp](https://github.com/roboticslab-uc3m/kinematics-dynamics/blob/974de241243c09612e8ab069317c9b6b76da6a2e/libraries/TeoYarp/AsibotSolver/TrajGen.hpp) file mostly as is, but it does not intervene at all in the compilation process. It might be re-used as an alternative to current trajectory generators at `BasicCartesianControl`, which in turn would require more work than it was initially planned at here.
